### PR TITLE
MongoDB Packs.

### PR DESCRIPTION
**Pull request by siniar1990**
First pack supports MongoDB version 2.6.
Second pack supports MongoDB version 3.0

Can you check if reletive links in README file are ok? It worked fine in my fork.

### CODE REVIEW

**Comment by mrud** [comment]
It doesn't look like it works. I think the pictures are wrong, try to load it directly via the raw url.

If you want to include images you probably also have to set raw=true or something similar, as described in http://webapps.stackexchange.com/questions/29602/markdown-to-insert-and-display-an-image-on-github-repo/39842#39842

**Comment by siniar1990** [comment]
Images were in a wrong format. My browser was still picking it up ok, but it didn't work for others. Can we try it now?

**Comment by mrud** [comment]
Is there any chance you could squash these commits together? Otherwise I can do it myself

**Comment by siniar1990** [comment]
I was trying to do it here, but unsuccessful. I'm only starting with GitHub and don't want to mess it up. It would be great if you could squash them for me this time and I'll look back to it.

**Comment by mrud** [comment]
Squashed and commited to master. Closing this merge request

**Pull request closed without merging**
